#!/usr/bin/env python3
"""Generate functions/api/chat.js from knowledge/*.md — a Cloudflare Pages
Function, deployed *alongside* the static site (same project, same domain,
same-origin so no CORS is needed), rather than a separate standalone Worker.

Cloudflare Pages Functions have no filesystem at request time, so the
knowledge base has to be baked into the JS bundle at generation time — the
same idea as build_site.py baking content/site.json into HTML. Re-run this
whenever a knowledge/*.md file changes, then redeploy the site as usual
(this file ships as part of the site's own source).

Usage:
    python3 scripts/generate_pages_function.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _chat_context import MAX_MESSAGE_CHARS, MODEL, build_system_instruction  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / 'functions' / 'api'

FUNCTION_TEMPLATE = '''\
// AUTO-GENERATED by scripts/generate_pages_function.py from knowledge/*.md —
// do not hand-edit; re-run the generator and redeploy instead. Cloudflare
// Pages Function, served at /api/chat on the same domain as the static
// site (same-origin, no CORS needed). Add GEMINI_API_KEY as a Pages
// environment variable/secret (Settings -> Environment variables) —
// never in this file, never in git.

const MODEL = {model!r};
const MAX_MESSAGE_CHARS = {max_chars};
const SYSTEM_INSTRUCTION = {system_instruction};

async function callGemini(message, lang, apiKey) {{
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${{MODEL}}:generateContent?key=${{apiKey}}`;
  const langHint = lang === 'zh' ? '\\n\\n(Reply in Chinese.)' : lang === 'en' ? '\\n\\n(Reply in English.)' : '';
  const payload = {{
    systemInstruction: {{parts: [{{text: SYSTEM_INSTRUCTION}}]}},
    contents: [{{role: 'user', parts: [{{text: message + langHint}}]}}],
    generationConfig: {{temperature: 0.3, maxOutputTokens: 300}},
  }};
  const res = await fetch(url, {{
    method: 'POST',
    headers: {{'Content-Type': 'application/json'}},
    body: JSON.stringify(payload),
  }});
  if (!res.ok) {{
    const detail = await res.text();
    console.error(`Gemini API error ${{res.status}}: ${{detail.slice(0, 300)}}`);
    throw new Error('upstream Gemini API error');
  }}
  const data = await res.json();
  const candidates = data.candidates || [];
  if (!candidates.length) throw new Error('Gemini returned no candidates (possibly blocked by safety filters)');
  const parts = candidates[0].content?.parts || [];
  const text = parts.map(p => p.text || '').join('').trim();
  if (!text) throw new Error('Gemini returned an empty response');
  return text;
}}

export async function onRequestPost(context) {{
  const {{ request, env }} = context;

  if (!env.GEMINI_API_KEY) {{
    console.error('GEMINI_API_KEY is not set as a Pages environment variable');
    return Response.json({{error: 'chat backend is not configured'}}, {{status: 500}});
  }}

  let body;
  try {{
    body = await request.json();
  }} catch (err) {{
    return Response.json({{error: 'invalid JSON'}}, {{status: 400}});
  }}

  let message = String(body.message || '').trim();
  const lang = String(body.lang || '').trim();
  if (!message) return Response.json({{error: 'message is required'}}, {{status: 400}});
  if (message.length > MAX_MESSAGE_CHARS) message = message.slice(0, MAX_MESSAGE_CHARS);

  try {{
    const reply = await callGemini(message, lang, env.GEMINI_API_KEY);
    return Response.json({{reply}});
  }} catch (err) {{
    console.error(`chat function error: ${{err.message}}`);
    return Response.json({{error: 'chat backend error'}}, {{status: 502}});
  }}
}}

export async function onRequestOptions() {{
  return new Response(null, {{
    status: 204,
    headers: {{
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    }},
  }});
}}
'''


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    system_instruction = build_system_instruction()
    out = FUNCTION_TEMPLATE.format(
        model=MODEL,
        max_chars=MAX_MESSAGE_CHARS,
        system_instruction=json.dumps(system_instruction, ensure_ascii=False),
    )
    dest = OUT_DIR / 'chat.js'
    dest.write_text(out, encoding='utf-8')
    print(f'Wrote {dest} ({len(out)} bytes, system instruction {len(system_instruction)} chars)')


if __name__ == '__main__':
    main()
