#!/usr/bin/env python3
"""Generate cloudflare-worker/worker.js from knowledge/*.md.

Cloudflare Workers have no filesystem at request time, so the knowledge base
has to be baked into the JS bundle at generation time — the same idea as
build_site.py baking content/site.json into HTML. Re-run this (and re-paste
the output into the Cloudflare dashboard, or redeploy via Wrangler) whenever
a knowledge/*.md file changes.

Usage:
    python3 scripts/generate_worker.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _chat_context import MAX_MESSAGE_CHARS, MODEL, build_system_instruction  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / 'cloudflare-worker'
ALLOWED_ORIGINS = [
    'https://tinkertechworld.com',
    'https://www.tinkertechworld.com',
    'http://127.0.0.1:4173',
    'http://localhost:4173',
]

WORKER_TEMPLATE = '''\
// AUTO-GENERATED by scripts/generate_worker.py from knowledge/*.md — do not
// hand-edit; re-run the generator and redeploy instead. This is the public,
// deployed counterpart of scripts/chat_server.py: same grounding, same
// anti-hallucination system prompt, same request/response shape. Paste this
// file into a Cloudflare Worker, then add GEMINI_API_KEY as a Worker secret
// (Settings -> Variables -> Add secret) — never in this file, never in git.

const MODEL = {model!r};
const MAX_MESSAGE_CHARS = {max_chars};
const ALLOWED_ORIGINS = new Set({origins});
const SYSTEM_INSTRUCTION = {system_instruction};

function corsHeaders(origin) {{
  const headers = {{}};
  if (ALLOWED_ORIGINS.has(origin)) {{
    headers['Access-Control-Allow-Origin'] = origin;
    headers['Vary'] = 'Origin';
  }}
  return headers;
}}

function jsonResponse(status, body, origin) {{
  return new Response(JSON.stringify(body), {{
    status,
    headers: {{'Content-Type': 'application/json', ...corsHeaders(origin)}},
  }});
}}

async function callGemini(message, lang, apiKey) {{
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${{MODEL}}:generateContent?key=${{apiKey}}`;
  const langHint = lang === 'zh' ? '\\n\\n(Reply in Chinese.)' : lang === 'en' ? '\\n\\n(Reply in English.)' : '';
  const payload = {{
    systemInstruction: {{parts: [{{text: SYSTEM_INSTRUCTION}}]}},
    contents: [{{role: 'user', parts: [{{text: message + langHint}}]}}],
    generationConfig: {{temperature: 0.3, maxOutputTokens: 300}},
  }};
  const res = await fetch(url, {{
    method: 'POST',
    headers: {{'Content-Type': 'application/json'}},
    body: JSON.stringify(payload),
  }});
  if (!res.ok) {{
    const detail = await res.text();
    console.error(`Gemini API error ${{res.status}}: ${{detail.slice(0, 300)}}`);
    throw new Error('upstream Gemini API error');
  }}
  const data = await res.json();
  const candidates = data.candidates || [];
  if (!candidates.length) throw new Error('Gemini returned no candidates (possibly blocked by safety filters)');
  const parts = candidates[0].content?.parts || [];
  const text = parts.map(p => p.text || '').join('').trim();
  if (!text) throw new Error('Gemini returned an empty response');
  return text;
}}

export default {{
  async fetch(request, env) {{
    const origin = request.headers.get('Origin') || '';

    if (request.method === 'OPTIONS') {{
      return new Response(null, {{
        status: 204,
        headers: {{
          ...corsHeaders(origin),
          'Access-Control-Allow-Methods': 'POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type',
        }},
      }});
    }}

    const url = new URL(request.url);
    if (request.method !== 'POST' || url.pathname !== '/api/chat') {{
      return jsonResponse(404, {{error: 'not found'}}, origin);
    }}

    if (!env.GEMINI_API_KEY) {{
      console.error('GEMINI_API_KEY secret is not set on this Worker');
      return jsonResponse(500, {{error: 'chat backend is not configured'}}, origin);
    }}

    let body;
    try {{
      body = await request.json();
    }} catch (err) {{
      return jsonResponse(400, {{error: 'invalid JSON'}}, origin);
    }}

    let message = String(body.message || '').trim();
    const lang = String(body.lang || '').trim();
    if (!message) return jsonResponse(400, {{error: 'message is required'}}, origin);
    if (message.length > MAX_MESSAGE_CHARS) message = message.slice(0, MAX_MESSAGE_CHARS);

    try {{
      const reply = await callGemini(message, lang, env.GEMINI_API_KEY);
      return jsonResponse(200, {{reply}}, origin);
    }} catch (err) {{
      console.error(`chat worker error: ${{err.message}}`);
      return jsonResponse(502, {{error: 'chat backend error'}}, origin);
    }}
  }},
}};
'''


def main():
    OUT_DIR.mkdir(exist_ok=True)
    system_instruction = build_system_instruction()
    out = WORKER_TEMPLATE.format(
        model=MODEL,
        max_chars=MAX_MESSAGE_CHARS,
        origins=json.dumps(ALLOWED_ORIGINS),
        system_instruction=json.dumps(system_instruction, ensure_ascii=False),
    )
    dest = OUT_DIR / 'worker.js'
    dest.write_text(out, encoding='utf-8')
    print(f'Wrote {dest} ({len(out)} bytes, system instruction {len(system_instruction)} chars)')


if __name__ == '__main__':
    main()
